const map=L.map('map').setView([19.38,-99.14],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);let data=[],filtered=[],markers=L.markerClusterGroup(),markerByCct={};map.addLayer(markers);
const metrics={pct_sobrepeso_obesidad:{label:'Sobrepeso u obesidad',unit:'%'},pct_caries:{label:'Caries',unit:'%'},pct_visual:{label:'Problemas visuales',unit:'%'},imc_promedio:{label:'IMC promedio',unit:''},completitud:{label:'Completitud',unit:'%'},prioridad_atencion:{label:'Prioridad de atención',unit:''},alertas_promedio:{label:'Alertas múltiples',unit:''}};
const colors=['#31965b','#e0b52b','#e67e22','#c83f3f'];
function num(v,d=1){return v==null||Number.isNaN(+v)?'Sin dato':(+v).toLocaleString('es-MX',{maximumFractionDigits:d})}function currentMetric(){let g=queryGroup.value;return g==='priority'?'prioridad_atencion':g==='alerts'?'alertas_promedio':healthMetric.value}function values(metric,rows=data){return rows.map(r=>+r[metric]).filter(Number.isFinite).sort((a,b)=>a-b)}function qs(metric){let a=values(metric);if(!a.length)return[0,0,0];let q=p=>a[Math.min(a.length-1,Math.floor((a.length-1)*p))];return[q(.25),q(.5),q(.75)]}function category(v,metric){if(v==null||!Number.isFinite(+v))return 'Sin dato';let q=qs(metric),x=+v;return x<=q[0]?'Bajo':x<=q[1]?'Medio':x<=q[2]?'Alto':'Muy alto'}function color(v,m){let c=category(v,m);return c==='Sin dato'?'#84939b':colors[['Bajo','Medio','Alto','Muy alto'].indexOf(c)]}
function populate(){[...new Set(data.map(x=>x.alcaldia).filter(Boolean))].sort().forEach(v=>filterAlcaldia.add(new Option(v,v)));[...new Set(data.map(x=>x.REF_CICLO_ESCOLAR).filter(Boolean))].sort().forEach(v=>filterCycle.add(new Option(v,v)));data.forEach(r=>{cctList.append(new Option('',r.CVE_ESCUELA_ATENCION));nameList.append(new Option('',r.NOM_ESCUELA_ATENCION))})}
function apply(){let m=currentMetric();filtered=data.filter(r=>(!filterAlcaldia.value||r.alcaldia===filterAlcaldia.value)&&(!filterCycle.value||r.REF_CICLO_ESCOLAR===filterCycle.value)&&(!searchCct.value||r.CVE_ESCUELA_ATENCION.toUpperCase().includes(searchCct.value.toUpperCase()))&&(!searchName.value||r.NOM_ESCUELA_ATENCION.toUpperCase().includes(searchName.value.toUpperCase()))&&(!filterPriority.value||category(r.prioridad_atencion,'prioridad_atencion')===filterPriority.value)&&(!filterAlerts.value||category(r.alertas_promedio,'alertas_promedio')===filterAlerts.value));render(m)}
function render(m){markers.clearLayers();markerByCct={};filtered.forEach(r=>{if(!Number.isFinite(+r.latitud)||!Number.isFinite(+r.longitud))return;let marker=L.circleMarker([r.latitud,r.longitud],{radius:7,weight:1,color:'#fff',fillColor:color(r[m],m),fillOpacity:.9});marker.on('click',()=>showDetail(r,m));markers.addLayer(marker);markerByCct[r.CVE_ESCUELA_ATENCION]=marker});updateLegend(m);updateKpis(m)}
function updateLegend(m){legendTitle.textContent=metrics[m].label;let q=qs(m);legendBody.innerHTML=['Bajo','Medio','Alto','Muy alto'].map((c,i)=>`<div class="legend-row"><span class="dot" style="background:${colors[i]}"></span>${c}${i<3?` (hasta ${num(q[i],2)})`:''}</div>`).join('')+'<div class="legend-row"><span class="dot" style="background:#84939b"></span>Sin dato</div>'}
function avg(col){let a=filtered.map(r=>+r[col]).filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}function updateKpis(m){kSchools.textContent=filtered.length.toLocaleString('es-MX');kEnrollment.textContent=filtered.reduce((s,r)=>s+(+r.matricula||0),0).toLocaleString('es-MX');kImc.textContent=num(avg('imc_promedio'),2);kMetric.textContent=num(avg(m),2)+(metrics[m].unit||'');kMetricLabel.textContent='Promedio: '+metrics[m].label}
function box(label,value,unit=''){return `<div class="info"><small>${label}</small><strong>${num(value,2)}${value==null?'':unit}</strong></div>`}function showDetail(r,m){detailTitle.textContent=r.NOM_ESCUELA_ATENCION;let cat=category(r[m],m),bg=color(r[m],m);detailBody.innerHTML=`<div class="info-grid">${box('CCT',r.CVE_ESCUELA_ATENCION)}${box('Turno',r.REF_TURNO_ATENCION)}${box('Ciclo',r.REF_CICLO_ESCOLAR)}${box('Matrícula',r.matricula, '')}${box('Alcaldía',r.alcaldia)}</div><h3 class="section-title">Indicadores</h3><div class="info-grid">${box('IMC promedio',r.imc_promedio)}${box('Sobrepeso u obesidad',r.pct_sobrepeso_obesidad,'%')}${box('Caries',r.pct_caries,'%')}${box('Problemas visuales',r.pct_visual,'%')}${box('Alertas múltiples',r.alertas_promedio)}${box('Prioridad de atención',r.prioridad_atencion)}${box('Completitud',r.completitud,'%')}</div><h3 class="section-title">Semáforo del indicador seleccionado</h3><div class="semaphore" style="background:${bg}">${metrics[m].label}: ${cat} · ${num(r[m],2)}${metrics[m].unit}</div>`;detail.classList.add('open')}
queryGroup.onchange=()=>{healthWrap.classList.toggle('hidden',queryGroup.value!=='health');apply()};healthMetric.onchange=apply;applyFilters.onclick=apply;clearFilters.onclick=()=>{[filterAlcaldia,filterCycle,filterPriority,filterAlerts].forEach(x=>x.value='');searchCct.value='';searchName.value='';apply()};closeDetail.onclick=()=>detail.classList.remove('open');hideMenu.onclick=()=>{sidebar.classList.add('hidden');showMenu.classList.remove('hidden');map.invalidateSize()};showMenu.onclick=()=>{sidebar.classList.remove('hidden');showMenu.classList.add('hidden');map.invalidateSize()};searchCct.onchange=()=>{apply();let r=filtered.find(x=>x.CVE_ESCUELA_ATENCION===searchCct.value);if(r){map.setView([r.latitud,r.longitud],16);showDetail(r,currentMetric())}};searchName.onchange=()=>{apply();let r=filtered.find(x=>x.NOM_ESCUELA_ATENCION===searchName.value);if(r){map.setView([r.latitud,r.longitud],16);showDetail(r,currentMetric())}};
fetch('data/salud_escolar.json').then(r=>r.json()).then(d=>{data=d;filtered=d;populate();apply()}).catch(e=>alert('No fue posible cargar la base de salud: '+e));
